# Generated by Django 5.0.6 on 2024-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexplainer',
            name='system_role',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
