# Generated by Django 5.0.6 on 2024-05-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_codeexplainer_system_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeexplainer',
            name='system_role',
        ),
    ]
