# Generated by Django 5.0.6 on 2024-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_codeexplainer_system_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexplainer',
            name='system_role',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
